import { readFileSync } from 'node:fs';
import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin();

/**
 * Legacy redirects.
 *
 * sonycolorlab.app was a single-page app that addressed recipes with a **query
 * parameter**, not a path — `recipe-service.js` did
 * `newUrl.searchParams.set('id', ...)`, and the share button built
 * `origin + ?id=<recipeId>`. So every link already shared in Facebook groups
 * looks like `https://sonycolorlab.app/?id=scl-001`, never `/recipe/scl-001`.
 *
 * A path-based redirect map would therefore have caught nothing.
 *
 * These only fire for traffic that reaches this app, so at cutover the old
 * hostname must resolve here (or carry an equivalent rule at the CDN).
 */
function legacyRedirects() {
  const recipes = JSON.parse(readFileSync('data/recipes.seed.json', 'utf8')) as {
    slug: string;
    legacyId: string | null;
  }[];

  return recipes
    .filter((r): r is { slug: string; legacyId: string } => Boolean(r.legacyId))
    .map((r) => ({
      source: '/',
      has: [{ type: 'query' as const, key: 'id', value: r.legacyId }],
      destination: `/recipe/${r.slug}`,
      permanent: true,
    }));
}

const supabaseHost = process.env.NEXT_PUBLIC_SUPABASE_URL
  ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).hostname
  : undefined;

/**
 * The hosts the product catalogue's photography comes from.
 *
 * Every one of them is named explicitly, and the list stays closed for the
 * reason the Supabase entry below already gives: an open pattern turns
 * `/_next/image` into a proxy for arbitrary URLs.
 *
 * `remotePatterns` is not what serves these any more — `images.loader` below
 * took `/_next/image` out of the path entirely — but the list is kept, and kept
 * closed, because it is the only written record of which hosts the catalogue is
 * allowed to reference. Restoring the optimizer means restoring its guard, and
 * `www.bhphotovideo.com` is deliberately absent: it answers hotlinked requests
 * with 403, and the 12 gallery URLs that named it now point at the CDN host
 * that serves the same files.
 */
const productImageHosts = ['static.bhphoto.com', 'www.sony.com.vn', 'sony.scene7.com'];

const nextConfig: NextConfig = {
  images: {
    /* Vercel's optimizer is out of the path: its quota ran out and every
       `/_next/image` request answered 402, breaking all 94 wiki photos at once
       while the originals stayed 200 at the CDN. The loader asks B&H for the
       size variant it already publishes instead. See the file's header. */
    loader: 'custom',
    loaderFile: './src/lib/images/catalogue-loader.ts',
    // Only the project's own Storage host, plus the catalogue's CDNs. Storage
    // is left out when Supabase is not configured, so a misconfigured deploy
    // cannot silently proxy arbitrary URLs.
    remotePatterns: [
      ...(supabaseHost
        ? [
            {
              protocol: 'https' as const,
              hostname: supabaseHost,
              pathname: '/storage/v1/object/public/**',
            },
          ]
        : []),
      ...productImageHosts.map((hostname) => ({ protocol: 'https' as const, hostname })),
    ],
    /* The catalogue never renders a product photo larger than a card, so the
       default ladder's big entries would only ever be generated by a crafted
       request. Both lists are trimmed to what the layouts actually ask for. */
    imageSizes: [16, 32, 48, 64, 96, 128, 256],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    // A catalogue photo is immutable — B&H publishes a new filename rather than
    // replacing bytes — so the optimizer's output can be cached for a year
    // instead of being re-derived every 60s.
    minimumCacheTTL: 31_536_000,
  },
  async redirects() {
    return legacyRedirects();
  },
};

export default withNextIntl(nextConfig);
