#!/usr/bin/env node
/**
 * Vendor Noto Sans into the repo.
 *
 *   npm run fonts:vendor
 *
 * Downloads the four weights this ecosystem uses, latin + vietnamese subsets
 * only, into public/fonts/noto-sans/ and writes noto-sans.css beside them.
 * The output is committed: nothing here loads from a CDN at runtime and
 * nothing uses next/font.
 *
 * Why not next/font: it hashes the family name into a per-app CSS variable,
 * so the four apps in this ecosystem cannot name the same face. They each
 * ended up with their own, which is exactly the uneven typography the
 * redesign was asked to fix. One literal family name — 'Noto Sans' — is the
 * only thing that makes four codebases agree.
 *
 * Why not latin-ext: measured at ~330KB and +2s LCP for languages nothing in
 * this ecosystem is written in. Vietnamese, on the other hand, is not
 * optional — without that subset the browser falls back mid-word on
 * diacritics, silently and with no build error.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const FAMILY = 'Noto Sans';
const WEIGHTS = [400, 500, 600, 800];
const SUBSETS = ['latin', 'vietnamese'];
const OUT_DIR = join(process.cwd(), 'public', 'fonts', 'noto-sans');

/* Google serves woff2 only to a UA it believes supports it. A plain fetch
   gets truetype URLs back, which are ~4x the bytes. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const WEIGHT_NAMES = {
  400: 'Regular',
  500: 'Medium',
  600: 'SemiBold',
  800: 'ExtraBold',
};

async function main() {
  const url =
    'https://fonts.googleapis.com/css2?family=' +
    FAMILY.replace(/ /g, '+') +
    ':wght@' +
    WEIGHTS.join(';') +
    '&display=swap';

  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error('Google Fonts returned ' + r.status + ' for ' + url);
    return r.text();
  });

  /* Each @font-face block is preceded by a comment naming its subset, which
     is the only place that information appears — the unicode-range alone
     would have to be pattern-matched. */
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]+\})/g)];
  if (blocks.length === 0) throw new Error('No @font-face blocks parsed — did the css2 format change?');

  await mkdir(OUT_DIR, { recursive: true });

  const faces = [];
  const seen = new Set();

  for (const [, subset, block] of blocks) {
    if (!SUBSETS.includes(subset)) continue;

    const weight = Number(block.match(/font-weight:\s*(\d+)/)?.[1]);
    const src = block.match(/src:\s*url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!weight || !src || !WEIGHTS.includes(weight)) continue;

    const file = 'NotoSans-' + WEIGHT_NAMES[weight] + '-' + subset + '.woff2';
    if (!seen.has(file)) {
      const bytes = await fetch(src, { headers: { 'User-Agent': UA } }).then((r) => {
        if (!r.ok) throw new Error('Font file returned ' + r.status + ' for ' + src);
        return r.arrayBuffer();
      });
      await writeFile(join(OUT_DIR, file), Buffer.from(bytes));
      seen.add(file);
      console.log('  ' + file + '  ' + Math.round(bytes.byteLength / 1024) + 'KB');
    }

    faces.push(
      [
        '@font-face {',
        "  font-family: '" + FAMILY + "';",
        '  font-style: normal;',
        '  font-weight: ' + weight + ';',
        /* swap, not optional: a 13px floor means the fallback metrics are
           close enough that a swap is less disruptive than invisible text. */
        '  font-display: swap;',
        "  src: url('./" + file + "') format('woff2');",
        '  unicode-range: ' + range + ';',
        '}',
      ].join('\n'),
    );
  }

  if (faces.length === 0) throw new Error('Parsed no usable faces — check WEIGHTS/SUBSETS.');

  const header = [
    '/* Generated by scripts/vendor-fonts.mjs — do not edit.',
    ' *',
    ' * ' + FAMILY + ' · weights ' + WEIGHTS.join(', ') + ' · subsets ' + SUBSETS.join(' + ') + '.',
    ' * Committed on purpose: this is the only face in the ecosystem and it must',
    ' * resolve identically in all four apps, offline and on first paint.',
    ' *',
    ' * Regenerate: npm run fonts:vendor',
    ' */',
    '',
  ].join('\n');

  await writeFile(join(OUT_DIR, 'noto-sans.css'), header + faces.join('\n\n') + '\n');
  console.log('\n  noto-sans.css  ' + faces.length + ' faces\n');
}

main().catch((err) => {
  console.error('\nfonts:vendor failed —', err.message, '\n');
  process.exit(1);
});
