/**
 * Scanner for the three design-system rules that can be checked mechanically.
 *
 * The Alpha design system states nine rules. Six of them ("separate layers with
 * light, not strokes", "uppercase only at label size") need eyes on a screen.
 * Three are countable, and those three are the ones that had quietly spread to
 * hundreds of call sites while every review passed:
 *
 *   below-floor  a font size under 13px. The ecosystem had drifted to 9px,
 *                10px, 11px and 0.65rem — on the line naming the person who
 *                contributed the photograph.
 *   mono         a second font family. `.tabular` already aligns a column of
 *                camera values using Noto Sans' real tabular figures, so mono
 *                buys nothing and costs the "the fonts don't match" review.
 *   palette      a Tailwind default colour (`amber-400`, `sky-300`, …). These
 *                are sRGB and sit visibly outside an OKLCH interface — and
 *                red, yellow and green are Canon's, Nikon's and Fuji's
 *                signatures, which is a bad look on a Sony tool.
 *
 * This module only counts. `floor.test.ts` compares the counts to a recorded
 * baseline, which is what makes the rules enforceable before the ~950 existing
 * call sites are fixed: the number may not go up, and every time it goes down
 * the drop is visible in the baseline diff.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
export const REPO_ROOT = resolve(HERE, '..', '..')

/** 13px at a 16px root. Below this nothing renders. */
export const FLOOR_PX = 13

export type Rule = 'belowFloor' | 'mono' | 'palette'

export interface Violation {
  readonly file: string
  readonly line: number
  readonly rule: Rule
  /** The offending text, for a failure message someone can act on. */
  readonly text: string
}

export type Counts = Readonly<Record<Rule, number>>
export type Baseline = Readonly<Record<string, Counts>>

/**
 * Roots to scan, repo-relative.
 *
 * `packages/colorlab-tokens/src` is in scope on purpose and is not an
 * afterthought: the single worst violation in the ecosystem is `.eyebrow` at
 * `font-size: 0.725rem` — 11.6px — in the SHARED primitive, which means all
 * three apps inherit a sub-floor eyebrow and no amount of fixing call sites in
 * this repo would have reached it.
 */
const ROOTS = ['src', 'packages/colorlab-tokens/src']

/**
 * Excluded, each for a reason that is not "it was inconvenient":
 *
 *   src/app/vendor          generated by `npm run tokens:emit`; token-drift.test.ts
 *                           already fails if it disagrees with the source, and a
 *                           violation here is really a violation in the source.
 *   packages/…/dist          same, one copy further out.
 *   src/design               this scanner names every Tailwind colour it hunts
 *                           for, and its test asserts on sample strings. Left in
 *                           scope it would report itself. Nothing else lives here.
 */
const EXCLUDED_DIRS = new Set(['vendor', 'dist', 'node_modules', 'design'])

const EXTENSIONS = ['.ts', '.tsx', '.css']

function walk(dir: string, out: string[]): string[] {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry)) walk(path, out)
      continue
    }
    if (EXTENSIONS.some((extension) => entry.endsWith(extension))) out.push(path)
  }
  return out
}

export function sourceFiles(): string[] {
  return ROOTS.flatMap((root) => walk(join(REPO_ROOT, root), []))
    .map((path) => relative(REPO_ROOT, path).split(sep).join('/'))
    .sort()
}

/* --------------------------------------------------------------------------
   Rules
-------------------------------------------------------------------------- */

/**
 * Tailwind's `text-xs` is 0.75rem — 12px, under the floor. The other named
 * steps (`text-sm` at 14px and up) are fine, and there is no `text-2xs`.
 */
const TAILWIND_NAMED_BELOW_FLOOR = /\btext-xs\b/g

/** `text-[10px]`, `text-[0.65rem]`. Arbitrary values, which is where most are. */
const ARBITRARY_SIZE = /\btext-\[(\d*\.?\d+)(px|rem)\]/g

/** A raw declaration in a stylesheet: `font-size: 0.725rem`. */
const CSS_FONT_SIZE = /font-size:\s*(\d*\.?\d+)(px|rem)/g

/**
 * Deliberately not matching `em`: it resolves against the parent, so 0.75em is
 * only a violation depending on where it lands, and a guard that guesses is a
 * guard that gets muted. There are none in this repo; if one appears, the
 * reviewer catches it.
 */
function toPx(value: string, unit: string): number {
  return unit === 'rem' ? Number(value) * 16 : Number(value)
}

/** The `font-mono` utility, and any hand-rolled read of the variable. */
const MONO = /\bfont-mono\b|var\(--font-mono\)/g

/**
 * A Tailwind default palette colour on any utility that takes one. Matches the
 * full `<utility>-<hue>-<step>` shape so that prose, a variable named `slate`,
 * or one of our own tokens cannot trip it.
 */
const PALETTE =
  /\b(?:bg|text|border|ring|from|to|via|shadow|fill|stroke|outline|decoration|accent|caret|divide|placeholder)-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d{2,3}\b/g

function lineOf(source: string, index: number): number {
  let line = 1
  for (let i = 0; i < index; i += 1) if (source[i] === '\n') line += 1
  return line
}

function collect(
  source: string,
  file: string,
  pattern: RegExp,
  rule: Rule,
  accept: (match: RegExpExecArray) => boolean = () => true,
): Violation[] {
  const found: Violation[] = []
  // Fresh lastIndex per call: these are module-level /g regexes and a shared
  // one silently skips matches on the second file it sees.
  pattern.lastIndex = 0
  let match = pattern.exec(source)
  while (match !== null) {
    if (accept(match)) {
      found.push({ file, line: lineOf(source, match.index), rule, text: match[0] })
    }
    match = pattern.exec(source)
  }
  return found
}

/**
 * Blanks out comment bodies, preserving newlines so every reported line number
 * still points at the right line.
 *
 * A guard that fires on its own documentation gets muted, not obeyed — the same
 * lesson `token-drift.test.ts` records, where a scan of the token source failed
 * on `#040406` written inside a `comment:` string describing the page
 * background. Without this, the three files that *explain* these rules were the
 * last three files reported as breaking them: tokens.ts naming `text-[9px]`,
 * `text-[10px]` and `text-[0.65rem]` in the sentence saying they fail the
 * build; globals.css saying what replaced `--font-mono`; and color.ts recording
 * that `text-amber-400` and `text-emerald-400` were deleted.
 *
 * Strings are deliberately NOT stripped. A Tailwind class always lives in one,
 * so stripping them would blind the scanner to every real violation.
 */
function stripComments(source: string): string {
  const blank = (text: string) => text.replace(/[^\n]/g, ' ')
  return source
    .replace(/\/\*[\s\S]*?\*\//g, blank)
    .replace(/(^|[^:])\/\/[^\n]*/g, (match, lead: string) => lead + blank(match.slice(lead.length)))
}

export function scanSource(source: string, file: string): Violation[] {
  const underFloor = (match: RegExpExecArray) => toPx(match[1], match[2]) < FLOOR_PX
  const code = stripComments(source)

  return [
    ...collect(code, file, TAILWIND_NAMED_BELOW_FLOOR, 'belowFloor'),
    ...collect(code, file, ARBITRARY_SIZE, 'belowFloor', underFloor),
    ...collect(code, file, CSS_FONT_SIZE, 'belowFloor', underFloor),
    ...collect(code, file, MONO, 'mono'),
    ...collect(code, file, PALETTE, 'palette'),
  ].sort((a, b) => a.line - b.line)
}

export function scanRepo(): Violation[] {
  return sourceFiles().flatMap((file) =>
    scanSource(readFileSync(join(REPO_ROOT, file), 'utf8'), file),
  )
}

/** Per-file counts, omitting clean files so the baseline shrinks as work lands. */
export function tally(violations: readonly Violation[]): Baseline {
  const baseline: Record<string, { belowFloor: number; mono: number; palette: number }> = {}
  for (const violation of violations) {
    baseline[violation.file] ??= { belowFloor: 0, mono: 0, palette: 0 }
    baseline[violation.file][violation.rule] += 1
  }
  return Object.fromEntries(Object.entries(baseline).sort(([a], [b]) => a.localeCompare(b)))
}

export function totals(baseline: Baseline): Counts {
  return Object.values(baseline).reduce(
    (sum, counts) => ({
      belowFloor: sum.belowFloor + counts.belowFloor,
      mono: sum.mono + counts.mono,
      palette: sum.palette + counts.palette,
    }),
    { belowFloor: 0, mono: 0, palette: 0 },
  )
}
